server:
  port: 88
security:
  basic:
    enabled: false

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3307/world?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=oa
    username: sa
    password: 123456
