server:
  port: 88
security:
  basic:
    enabled: false

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3307/world?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=oa
    username: sa
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail:
    host: smtp.163.com1
    port: 251
    username: wangxinming1000@163.com
    password: aszcM146
    enable: false
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
contract.template.path: F:\tmp\oa\
openoffice.org.path: C:/Program Files (x86)/OpenOffice 4
