use oa;
if exists ( select *
 from  sysobjects
 where name = 'OA_USER'
 and type = 'U')
 drop table OA_USER
go

CREATE TABLE OA_USER
(
  USER_ID           INT IDENTITY PRIMARY KEY,
  USER_NAME         NVARCHAR(200) UNIQUE NOT NULL ,
  GROUP_ID          INT DEFAULT 0,
  USER_MOBILE       NVARCHAR(20) UNIQUE,
  USER_EMAIL        NVARCHAR(200),
  USER_PWD          NVARCHAR(200),
  ENTERPRISE_ID     INT DEFAULT 0,
  USER_COMPANY      NVARCHAR(200),
  USER_DEPARTMENT   NVARCHAR(200),
  USER_POSITION     NVARCHAR(200),
  USER_ADDRESS      NVARCHAR(200),
  USER_POSTCODE     NVARCHAR(200),
  USER_WEIXIN       NVARCHAR(100),
  PARENT_ID         INT DEFAULT 0,
  USER_STATUS       INT DEFAULT 0,
  USER_CREATETIME   DATETIME
)
GO
/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'用户表', N'user', N'dbo', N'table', N'OA_USER', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'用户编号', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户名称', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户组编号', N'user', N'dbo', N'table', N'OA_USER', N'column', N'GROUP_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户手机号码', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_MOBILE';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户邮箱地址', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_EMAIL';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户密码', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_PWD';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户所属公司', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_COMPANY';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户部门', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_DEPARTMENT';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户岗位', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_POSITION';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户住址', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_ADDRESS';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户邮编', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_POSTCODE';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户微信号', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_WEIXIN';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户状态', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_STATUS';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户创建时间', N'user', N'dbo', N'table', N'OA_USER', N'column', N'USER_CREATETIME';

insert OA_USER (USER_NAME,USER_PWD,USER_STATUS,USER_CREATETIME) values ('admin','202CB962AC59075B964B07152D234B70',1,'2018-04-23 11:06:21.517');

if exists ( select *
 from  sysobjects
 where name = 'OA_CONTRACT_TEMPLATE'
 and type = 'U')
 drop table OA_CONTRACT_TEMPLATE
go
CREATE TABLE OA_CONTRACT_TEMPLATE
(
  TEMPLATE_ID         INT IDENTITY PRIMARY KEY,
  TEMPLATE_NAME       NVARCHAR(255) UNIQUE ,
  USER_ID             INT,
  TEMPLATE_STATUS     INT,
  TEMPLATE_HTML       TEXT,
  TEMPLATE_DES        NVARCHAR(255),
  TEMPLATE_CREATETIME DATETIME
)
GO
/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'合同模板表', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'模板编号', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'TEMPLATE_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'模板名称', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'TEMPLATE_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'创建模板', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'USER_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'模板启用状态', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'TEMPLATE_STATUS';
EXECUTE sp_addextendedproperty N'MS_Description', N'模板内容', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'TEMPLATE_HTML';
EXECUTE sp_addextendedproperty N'MS_Description', N'模板描述信息', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'TEMPLATE_DES';
EXECUTE sp_addextendedproperty N'MS_Description', N'模板创建时间', N'user', N'dbo', N'table', N'OA_CONTRACT_TEMPLATE', N'column', N'TEMPLATE_CREATETIME';

INSERT INTO OA_CONTRACT_TEMPLATE(TEMPLATE_NAME,USER_ID,TEMPLATE_STATUS,TEMPLATE_HTML,TEMPLATE_CREATETIME) VALUES ('自定义合同',1,1,'<DIV style="margin-top: 25px;"></DIV>','2018-04-23 11:06:21.517');
/*
<DIV style="margin-top: 25px;">
                <div class="row" id="customFile">
                    <div class="col-md-6">
                        <input id="file" type="file" accept=".doc,.docx" name="file" class="" style="" value="选择word文档">
                    </div>
                    <div class="col-md-6">
                        　　<input type="submit" onclick="uploadFile();" name="submit" id="submit" ng-hide="loginUserMenuMap[currentView]" value="上传" class="btn btn-primary btn-lg" >  <span id="sendStatus"></span>
                    </div>
                </div>
		<div style="margin-top: 25px;margin-bottom: 20px;" id="download">
		</div>
</DIV>
*/
if exists ( select *
 from  sysobjects
 where name = 'OA_DEPLOYMENT_TEMPLATE_RELATION'
 and type = 'U')
 drop table OA_DEPLOYMENT_TEMPLATE_RELATION
go
CREATE TABLE OA_DEPLOYMENT_TEMPLATE_RELATION
(
  RELATION_ID           INT IDENTITY PRIMARY KEY,
  RELATION_DEPLOYMENTID NVARCHAR(255),
  RELATION_TEMPLATEID   INT,
  RELATION_CREATETIME   DATETIME
)
GO

/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'部署流程与合同模板关联表', N'user', N'dbo', N'table', N'OA_DEPLOYMENT_TEMPLATE_RELATION', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'关联编号', N'user', N'dbo', N'table', N'OA_DEPLOYMENT_TEMPLATE_RELATION', N'column', N'RELATION_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'部署流程编号', N'user', N'dbo', N'table', N'OA_DEPLOYMENT_TEMPLATE_RELATION', N'column', N'RELATION_DEPLOYMENTID';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同模板编号', N'user', N'dbo', N'table', N'OA_DEPLOYMENT_TEMPLATE_RELATION', N'column', N'RELATION_TEMPLATEID';
EXECUTE sp_addextendedproperty N'MS_Description', N'关联创建时间', N'user', N'dbo', N'table', N'OA_DEPLOYMENT_TEMPLATE_RELATION', N'column', N'RELATION_CREATETIME';

if exists ( select *
 from  sysobjects
 where name = 'OA_FORM_PROPERTIES'
 and type = 'U')
 drop table OA_FORM_PROPERTIES
go
CREATE TABLE OA_FORM_PROPERTIES
(
  PROPERTIES_ID INT IDENTITY PRIMARY KEY,
  TEMPLATE_ID   INT,
  FIELD_NAME    NVARCHAR(255),
  FIELD_MD5     NVARCHAR(255) NOT NULL,
  FIELD_TYPE    NVARCHAR(255),
  FIELD_VALID   NVARCHAR(255),
  STATUS        INT,
  CREATE_TIME   DATETIME
)
GO

/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'合同模板表单项', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'表单项编号', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'PROPERTIES_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同模板编号', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'TEMPLATE_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'表单项名称', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'FIELD_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'表单项唯一值', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'FIELD_MD5';
EXECUTE sp_addextendedproperty N'MS_Description', N'表单项类型', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'FIELD_TYPE';
EXECUTE sp_addextendedproperty N'MS_Description', N'表单项校验规则', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'FIELD_VALID';
EXECUTE sp_addextendedproperty N'MS_Description', N'表单项创建时间', N'user', N'dbo', N'table', N'OA_FORM_PROPERTIES', N'column', N'CREATE_TIME';

if exists ( select *
 from  sysobjects
 where name = 'OA_CONTRACT_CIRCULATION'
 and type = 'U')
 drop table OA_CONTRACT_CIRCULATION
go
CREATE TABLE OA_CONTRACT_CIRCULATION
(
  CONTRACT_ID     INT IDENTITY PRIMARY KEY,
  TEMPLATE_ID     NVARCHAR(255),
  CONTRACT_REOPEN INT,
  PROCESSINSTANCE_ID NVARCHAR(255) not null,
  CONTRACT_NAME   NVARCHAR(255),
  USER_ID         INT,
  CONTRACT_STATUS NVARCHAR(255),
  DESCRIPTION     NVARCHAR(255),
  CONTRACT_HTML   TEXT,
  CONTRACT_PDF    IMAGE,
  WORK_STATUS     INT,
  CREATE_TIME     DATETIME
)
GO

/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'合同流转表', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'合同编号', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'CONTRACT_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'模板编号', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'TEMPLATE_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'流程实例编号', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'PROCESSINSTANCE_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同名称', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'CONTRACT_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'用户编号', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'USER_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同流转状态', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'CONTRACT_STATUS';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同描述', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'DESCRIPTION';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同原始HTML', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'CONTRACT_HTML';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同PDF', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'CONTRACT_PDF';
EXECUTE sp_addextendedproperty N'MS_Description', N'开工状态', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'WORK_STATUS';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同创建时间', N'user', N'dbo', N'table', N'OA_CONTRACT_CIRCULATION', N'column', N'CREATE_TIME';

if exists ( select *
 from  sysobjects
 where name = 'OA_AUDIT'
 and type = 'U')
 drop table OA_AUDIT
go
CREATE TABLE OA_AUDIT
(
  AUDIT_ID     INT IDENTITY PRIMARY KEY,
  USER_NAME     NVARCHAR(255),
  CONTENT     NVARCHAR(500),
  CREATE_TIME     DATETIME
)
GO
/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'操作审计表', N'user', N'dbo', N'table', N'OA_AUDIT', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'操作审计编号', N'user', N'dbo', N'table', N'OA_AUDIT', N'column', N'AUDIT_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'操作内容', N'user', N'dbo', N'table', N'OA_AUDIT', N'column', N'CONTENT';
EXECUTE sp_addextendedproperty N'MS_Description', N'操作时间', N'user', N'dbo', N'table', N'OA_AUDIT', N'column', N'CREATE_TIME';


-- if exists ( select *
--  from  sysobjects
--  where name = 'OA_ORGANIZATION'
--  and type = 'U')
--  drop table OA_ORGANIZATION
-- go
-- CREATE TABLE OA_ORGANIZATION
-- (
--   ORGANIZATION_ID     INT IDENTITY PRIMARY KEY,
--   ORGANIZATION_NAME     NVARCHAR(255),
--   USER_ID     INT,
--   DESCRIBE         NVARCHAR(500),
--   CREATE_TIME     DATETIME
-- )
--
-- GO
-- /* 表注释 */
-- EXECUTE sp_addextendedproperty N'MS_Description', N'组织机构表', N'user', N'dbo', N'table', N'OA_ORGANIZATION', NULL, NULL;
-- /* 字段注释 */
-- EXECUTE sp_addextendedproperty N'MS_Description', N'组织编号', N'user', N'dbo', N'table', N'OA_ORGANIZATION', N'column', N'ORGANIZATION_ID';
-- EXECUTE sp_addextendedproperty N'MS_Description', N'组织名称', N'user', N'dbo', N'table', N'OA_ORGANIZATION', N'column', N'ORGANIZATION_NAME';
-- EXECUTE sp_addextendedproperty N'MS_Description', N'用户编号', N'user', N'dbo', N'table', N'OA_ORGANIZATION', N'column', N'USER_ID';
-- EXECUTE sp_addextendedproperty N'MS_Description', N'描述信息', N'user', N'dbo', N'table', N'OA_ORGANIZATION', N'column', N'DESCRIBE';
-- EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'OA_ORGANIZATION', N'column', N'CREATE_TIME';

if exists ( select *
 from  sysobjects
 where name = 'OA_GROUP'
 and type = 'U')
 drop table OA_GROUP
go
CREATE TABLE OA_GROUP
(
  GROUP_ID     INT IDENTITY PRIMARY KEY,
  GROUP_NAME     NVARCHAR(255),
  USER_ID        INT,
  PRIVILEGEIDS   NVARCHAR(500),
  DESCRIBE       NVARCHAR(500),
  STATUS         INT,
  CREATE_TIME     DATETIME
)
GO
/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'组织机构表', N'user', N'dbo', N'table', N'OA_GROUP', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'组织编号', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'GROUP_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'组织名称', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'GROUP_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'创建组用户编号', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'USER_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'权限信息记录', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'PRIVILEGEIDS';
EXECUTE sp_addextendedproperty N'MS_Description', N'描述信息', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'DESCRIBE';
EXECUTE sp_addextendedproperty N'MS_Description', N'组启用状态', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'STATUS';
EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'OA_GROUP', N'column', N'CREATE_TIME';

if exists ( select *
 from  sysobjects
 where name = 'OA_PRIVILEGE'
 and type = 'U')
 drop table OA_PRIVILEGE
go
CREATE TABLE OA_PRIVILEGE
(
  PRIVILEGE_ID     INT IDENTITY PRIMARY KEY,
  TYPE             NVARCHAR(100),
  NAME             NVARCHAR(100),
  CONTENT          NVARCHAR(500),
  DESCRIBE         NVARCHAR(500),
  CREATE_TIME      DATETIME
)
GO
/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'权限表', N'user', N'dbo', N'table', N'OA_PRIVILEGE', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'权限编号', N'user', N'dbo', N'table', N'OA_PRIVILEGE', N'column', N'PRIVILEGE_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'权限类型', N'user', N'dbo', N'table', N'OA_PRIVILEGE', N'column', N'TYPE';
EXECUTE sp_addextendedproperty N'MS_Description', N'权限名称', N'user', N'dbo', N'table', N'OA_PRIVILEGE', N'column', N'NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'权限内容', N'user', N'dbo', N'table', N'OA_PRIVILEGE', N'column', N'CONTENT';
EXECUTE sp_addextendedproperty N'MS_Description', N'描述信息', N'user', N'dbo', N'table', N'OA_PRIVILEGE', N'column', N'DESCRIBE';
EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'OA_PRIVILEGE', N'column', N'CREATE_TIME';

INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','新建用户','user','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','用户组管理','group','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','公司管理','enterprise','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','修改密码','password','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','合同模板管理','upload','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','合同模板字段检查','form','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','工作流定义','modeler','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','已发布流程','deployment','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','新合同建立','process','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','待处理申请','myProcess','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','我发起的申请','initiator','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','合同审核及批复','pending','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','归档文件查询','complete','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('menu','个人任务统计','privateReport','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','法务任务统计','fawuReport','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('menu','管理员日志查询','audit','2018-04-26 11:41:53.760');

INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','新建用户','user','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','用户组管理','group','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','公司管理','enterprise','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','修改密码','password','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','合同模板管理','upload','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('button','合同模板字段检查','form','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','工作流定义','modeler','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','已发布流程','deployment','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('button','新合同建立','process','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('button','待处理申请','myProcess','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','我发起的申请','initiator','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','合同审核及批复','pending','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('button','归档文件查询','complete','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME,CONTENT, CREATE_TIME) VALUES ('button','个人任务统计','privateReport','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','法务任务统计','fawuReport','2018-04-26 11:41:53.760');
INSERT INTO OA_PRIVILEGE (TYPE, NAME, CONTENT,CREATE_TIME) VALUES ('button','管理员日志查询','audit','2018-04-26 11:41:53.760');


if exists ( select *
 from  sysobjects
 where name = 'OA_ENTERPRISE'
 and type = 'U')
 drop table OA_ENTERPRISE
go
CREATE TABLE OA_ENTERPRISE
(
  ENTERPRISE_ID       INT IDENTITY PRIMARY KEY,
  COMPANY_NAME        NVARCHAR(100),
  COMPANY_SUBNAME     NVARCHAR(200),
  COMPANY_LOCATION    NVARCHAR(200),
  COMPANY_PROVINCE    NVARCHAR(20),
  COMPANY_CITY          NVARCHAR(50),
  COMPANY_OWNER         NVARCHAR(50),
  OWNER_MOBILE         NVARCHAR(20),
  COMPANY_STATUS      INT,
  CREATE_TIME      DATETIME
)
GO
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('天津分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('天津分公司(天津地铁5、6号线工程文化中心部分第2合同段项目经理部)','天津地铁5、6号线工程文化中心部分第2合同段项目经理部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(淞沪路三门路项目)','淞沪路三门路项目',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(周家嘴路隧道)','周家嘴路隧道',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(北横通道)','北横通道',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波镇海北仑)','宁波镇海北仑',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(上海轨道交通18号线工程)','上海轨道交通18号线工程两港截流合流总管改迁工程项经部、上海市轨道交通14号线工程（桂桥路站附属管幕结构段土建工程）顶管工程项目经理部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(15号线9标)','15号线9标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(10号线二期1标)','10号线二期1标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(14号线8、9、10标)','14号线8、9、10标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(18号线12标)','18号线12标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(上海隧道工程有限公司沿江通道越江隧道新建工程I标项目经理部)','上海隧道工程有限公司沿江通道越江隧道新建工程I标项目经理部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(杭州5号线SG5-15标)','杭州5号线SG5-15标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(杭州文一地下通道)','杭州文一地下通道',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(昆明市轨道交通2号线二期工程)','昆明市轨道交通2号线二期工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(昆明市轨道交通3号线二期工程)','昆明市轨道交通3号线二期工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(昆明市轨道交通4号线二期工程)','昆明市轨道交通4号线二期工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(昆明市轨道交通5号线二期工程)','昆明市轨道交通5号线二期工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(昆明市轨道交通6号线二期工程)','昆明市轨道交通6号线二期工程',1,'2018-06-20 12:10:32.607');


INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(南京地铁5号线项经部)','南京地铁5号线项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波3号线一期矩形盾构标)','宁波3号线一期矩形盾构标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波TJ4016标)','宁波TJ4016标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波顶管I标)','宁波顶管I标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(成山路顶管)','成山路顶管',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(南京地铁5号线TA02标)','南京地铁5号线TA02标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(14号线16标)','14号线16标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(隧道维护事业部)','隧道维护事业部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(维保事业部)','维保事业部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(诸光路隧道)','诸光路隧道',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(杭州地铁5号线sg5-15标拆复桥)','杭州地铁5号线sg5-15标拆复桥',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(杭州地铁5号线sg5-16标拆复桥)','杭州地铁5号线sg5-16标拆复桥',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(郑州4号线05标段施工队)','郑州4号线05标段施工队',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波TJ2218标)','宁波TJ2218标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(无锡3号线9标)','无锡3号线9标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(测量事业部)','测量事业部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波TJ4010标)','宁波TJ4010标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(乌鲁木齐地铁2号线)','乌鲁木齐地铁2号线',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(乌鲁木齐地铁3号线)','乌鲁木齐地铁3号线',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(乌鲁木齐地铁1、2、3号线)','乌鲁木齐地铁1、2、3号线',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(宁波TJ3101标)','宁波TJ3101标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('盾构工程分公司(武汉7号线8标小盾构)','武汉7号线8标小盾构',1,'2018-06-20 12:10:32.607');

INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(轨交15号线11标项经部)','轨交15号线11标项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(14号线8标项经部)','14号线8标项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(14号线9标项经部)','14号线9标项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(轨交15号线10-1标换乘大厅项经部)','轨交15号线10-1标换乘大厅项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(轨交15号线10标)','轨交15号线10标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(9号线三期2标14号线蓝天路站)','9号线三期2标14号线蓝天路站',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(18号线12标)','18号线12标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(14号线工程土建10标)','14号线工程土建10标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(上海轨交十号线二期1标)','上海轨交十号线二期1标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(14号线23标桂桥路站)','14号线23标桂桥路站',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(上海动物园综合客运交通枢纽)','上海动物园综合客运交通枢纽',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(硬X射线自由电子激光装置项目2标)','硬X射线自由电子激光装置项目2标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(13号线二期101标成山路站、10号线港城路停车场)','13号线二期101标成山路站、10号线港城路停车场',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('轨交项管部(东西通道浦东大道站)','东西通道浦东大道站',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('武汉分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('河南分公司','',1,'2018-06-20 12:10:32.607');

INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('河南分公司(郑州市轨道交通4号线工程土建施工05标段)','郑州市轨道交通4号线工程土建施工05标段',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('河南分公司(郑州航空港经济综合实验区（郑州新郑综合保税区）园博园片区综合管廊项目)','郑州航空港经济综合实验区（郑州新郑综合保税区）园博园片区综合管廊项目',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('河南分公司(郑州机许线05标)','郑州机许线05标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('河南分公司(郑州城郊线二期A合同段)','郑州城郊线二期A合同段',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('河南分公司(郑州控制性节点09标)','郑州控制性节点09标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('机械制造分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(虹桥污水处理厂、北翟路BD-1标、长宁区勾连工程)','虹桥污水处理厂、北翟路BD-1标、长宁区勾连工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(沿江通道越江隧道（江杨北路-牡丹江路）新建工程1标、虹桥商务核心区（二期）区域供能管沟工程)','沿江通道越江隧道（江杨北路-牡丹江路）新建工程1标、虹桥商务核心区（二期）区域供能管沟工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(陈行公路二期道路改建工程)','陈行公路二期道路改建工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(杨浦区154公租房)','杨浦区154公租房',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(18号线10标)','18号线10标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(尚贤坊保护性改造项目桩基础及地下连续墙工程)','尚贤坊保护性改造项目桩基础及地下连续墙工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(上海浦东国际机场三期扩建工程捷运系统车站及工作区间装修、安装和车辆基地工程)','上海浦东国际机场三期扩建工程捷运系统车站及工作区间装修、安装和车辆基地工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(竹园第一、第二污水处理厂提标改造工程)','竹园第一、第二污水处理厂提标改造工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(黄浦江上游水源地连通管工程C1标)','黄浦江上游水源地连通管工程C1标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(竹园第一、第二污水处理厂提标改造工程)','竹园第一、第二污水处理厂提标改造工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(长风生态养老院)','长风生态养老院',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(三林滨江南片区市政道路工程)','三林滨江南片区市政道路工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(蟠龙路（盈港东路—崧泽大道）改建工程)','蟠龙路（盈港东路—崧泽大道）改建工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(苏州河段深层排水调蓄管道系统工程试验段SS1.1标)','苏州河段深层排水调蓄管道系统工程试验段SS1.1标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(苏州河段深层排水调蓄管道系统工程试验段SS1.2标)','苏州河段深层排水调蓄管道系统工程试验段SS1.2标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(苏州河段深层排水调蓄管道系统工程试验段SS1.3标)','苏州河段深层排水调蓄管道系统工程试验段SS1.3标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(武宁路快速化改建工程Ⅱ标段)','武宁路快速化改建工程Ⅱ标段',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(前滩中心25-1北区2标（除桩基）)','前滩中心25-1北区2标（除桩基）',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政项管部(嘉松公路改建工程4标)','嘉松公路改建工程4标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部(北横2标)','北横2标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部(北横II标)','北横II标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部(滁州综合管廊二期)','滁州综合管廊二期',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部(沿江通道越江隧道新建工程II标)','沿江通道越江隧道新建工程II标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部(沿江通道I标项经部)','沿江通道I标项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('越江项管部(诸光路通道)','诸光路通道',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政设计院','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('市政设计院(景洪路（老沪闵路-华泾西规划二路）道路新建工程)','景洪路（老沪闵路-华泾西规划二路）道路新建工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('昆明分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('昆明分公司(昆明轨交2号线二期2标项经部)','昆明轨交2号线二期2标项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('昆明分公司(昆明轨交2号线二期3标项经部)','昆明轨交2号线二期3标项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('昆明分公司(成都天府国际机场航站区配套市政工程施工二标段)','成都天府国际机场航站区配套市政工程施工二标段',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('昆明分公司(昆明经济技术开发区呈黄路（北段）工程西辅线项目项经部)','昆明经济技术开发区呈黄路（北段）工程西辅线项目项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('昆明分公司(官渡区6号等13条路新建PPP项目项经部)','官渡区6号等13条路新建PPP项目项经部',1,'2018-06-20 12:10:32.607');

INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('台州分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('台州分公司(G228宁海西店至桃源段公路工程第一合同段项目经理部)','G228宁海西店至桃源段公路工程第一合同段项目经理部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('台州分公司(胜陆（胜山至陆埠）公路项目经理部)','胜陆（胜山至陆埠）公路项目经理部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('台州分公司(台州自地下综合管廊一期工程项目经理部)','台州自地下综合管廊一期工程项目经理部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('构件分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('杭绍台总承包部','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('杭绍台总承包部(杭绍台高速公路工程台州段1标段1工区项经部)','杭绍台高速公路工程台州段1标段1工区项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('杭绍台总承包部(杭绍台高速公路工程台州段1标段2工区项经部)','杭绍台高速公路工程台州段1标段2工区项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('杭绍台总承包部(杭绍台高速公路工程台州段1标段3工区项经部)','杭绍台高速公路工程台州段1标段3工区项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('杭绍台总承包部(杭绍台高速公路工程台州段2标段1工区项经部)','杭绍台高速公路工程台州段2标段1工区项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('杭绍台总承包部(杭绍台高速公路工程台州段2标段2工区项经部)','杭绍台高速公路工程台州段2标段2工区项经部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('江苏分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('江苏分公司(南京地铁宁溧线土建工程TA09标/浦口大桥北路快速化改造工程施工招标A1标)','南京地铁宁溧线土建工程TA09标/浦口大桥北路快速化改造工程施工招标A1标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('江苏分公司(南通一号线02标)','南通一号线02标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('江苏分公司(无锡地铁3号线一期工程09标土建工程)','无锡地铁3号线一期工程09标土建工程',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(总承包部)','总承包部',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(南京地铁5号线TA01标)','南京地铁5号线TA01标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(南京地铁5号线TA02标)','南京地铁5号线TA02标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(南京地铁5号线TA03标)','南京地铁5号线TA03标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(南京地铁5号线TA05标)','南京地铁5号线TA05标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(南京地铁5号线TA06标)','南京地铁5号线TA06标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('南京地铁5号线PPP项目总承包部(南京地铁5号线TA08标)','南京地铁5号线TA08标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江分公司','',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州2号线凤起路站)','杭州2号线凤起路站',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州南站)','杭州南站',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州5号线火车南站)','杭州5号线火车南站',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州5号线15标)','杭州5号线15标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州6号线9标)','杭州6号线9标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州文一路)','杭州文一路',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭绍城际铁路SG-6标)','杭绍城际铁路SG-6标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(宁波TJ2218标)','宁波TJ2218标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(宁波TJ3101标)','宁波TJ3101标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(杭州SG4-2-1标)','杭州SG4-2-1标',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(宁海38省道)','宁海38省道',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(温州市域铁路S2)','温州市域铁路S2',1,'2018-06-20 12:10:32.607');
INSERT into OA_ENTERPRISE(COMPANY_NAME,COMPANY_SUBNAME,COMPANY_STATUS,CREATE_TIME) VALUES ('浙江区域职业化(甬台温)','甬台温',1,'2018-06-20 12:10:32.607');


/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'企业表', N'user', N'dbo', N'table', N'OA_ENTERPRISE', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'公司编号', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'ENTERPRISE_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'公司名称', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'COMPANY_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'公司所在省区', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'COMPANY_PROVINCE';
EXECUTE sp_addextendedproperty N'MS_Description', N'公司所在市区', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'COMPANY_CITY';
EXECUTE sp_addextendedproperty N'MS_Description', N'公司负责人', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'COMPANY_OWNER';
EXECUTE sp_addextendedproperty N'MS_Description', N'公司负责人手机号码', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'OWNER_MOBILE';
EXECUTE sp_addextendedproperty N'MS_Description', N'公司状态', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'COMPANY_STATUS';
EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'OA_ENTERPRISE', N'column', N'CREATE_TIME';

if exists ( select *
 from  sysobjects
 where name = 'OA_ATTACHMENT'
 and type = 'U')
 drop table OA_ATTACHMENT
go
CREATE TABLE OA_ATTACHMENT
(
  ATTACHMENT_ID       INT IDENTITY PRIMARY KEY,
  CONTRACT_ID         INT,
  FILE_NAME            NVARCHAR(100),
  FILE_CONTENT        IMAGE,
  CREATE_TIME      DATETIME
)
GO
/* 表注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'附件信息表', N'user', N'dbo', N'table', N'OA_ATTACHMENT', NULL, NULL;
/* 字段注释 */
EXECUTE sp_addextendedproperty N'MS_Description', N'附件编号', N'user', N'dbo', N'table', N'OA_ATTACHMENT', N'column', N'ATTACHMENT_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'合同编号', N'user', N'dbo', N'table', N'OA_ATTACHMENT', N'column', N'CONTRACT_ID';
EXECUTE sp_addextendedproperty N'MS_Description', N'附件名称', N'user', N'dbo', N'table', N'OA_ATTACHMENT', N'column', N'FILE_NAME';
EXECUTE sp_addextendedproperty N'MS_Description', N'附件内容', N'user', N'dbo', N'table', N'OA_ATTACHMENT', N'column', N'FILE_CONTENT';
EXECUTE sp_addextendedproperty N'MS_Description', N'创建时间', N'user', N'dbo', N'table', N'OA_ATTACHMENT', N'column', N'CREATE_TIME';
-- /*表注释*/
-- SELECT [ColumnName] = [Columns].name ,
--        [Description] = [Properties].value,
--        [SystemTypeName] = [Types].name ,
--        [Precision] = [Columns].precision ,
--        [Scale] = [Columns].scale ,
--        [MaxLength] = [Columns].max_length ,
--        [IsNullable] = [Columns].is_nullable ,
--        [IsRowGUIDCol] = [Columns].is_rowguidcol ,
--        [IsIdentity] = [Columns].is_identity ,
--        [IsComputed] = [Columns].is_computed ,
--        [IsXmlDocument] = [Columns].is_xml_document
-- FROM    sys.tables AS [Tables]
--   INNER JOIN sys.columns AS [Columns] ON [Tables].object_id = [Columns].object_id
--   INNER JOIN sys.types AS [Types] ON [Columns].system_type_id = [Types].system_type_id
--                                      AND is_user_defined = 0
--                                      AND [Types].name <> 'sysname'
--   LEFT OUTER JOIN sys.extended_properties AS [Properties] ON [Properties].major_id = [Tables].object_id
--                                                              AND [Properties].minor_id = [Columns].column_id
--                                                              AND [Properties].name = 'MS_Description'
-- WHERE   [Tables].name ='OA_USER' -- and [Columns].name = '字段名'
-- ORDER BY [Columns].column_id


